EightQueenProblem/Models/ChessModel/Chess.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EightQueenProblem.Models.ChessModel
{

    public class Chess
    {
        public int Size { get; set; }

        public List<Queen> QueenPositions;
    }
}

EightQueenProblem/Models/ChessModel/Queen.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EightQueenProblem.Models.ChessModel
{
    public class Queen
    {
        public int row { get; set; }
        public int col { get; set; }
    }
}

EightQueenProblem/Models/ErrorViewModel.cs
using System;

namespace EightQueenProblem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EightQueenProblem/Controllers/SolveProblemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EightQueenProblem.Models.ChessModel;

namespace EightQueenProblem.Controllers
{
    public class SolveProblemController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ViewAllSolution([FromBody]Chess chess)
        {
            if(ModelState.IsValid)
            {
                return PartialView("_ViewAllSolution", chess);
            }
            return RedirectToAction("Index");
        }
    }
}

EightQueenProblem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EightQueenProblem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>
        /*.bg {
            background-image: url(images/img_body.jpg);
            background-color: hsla(0,0%,100%,0.90);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center;
            background-size: 100% 100%;
        }*/
    </style>

</head>
<body class="bg">
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EightQueenProblem</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>*@

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">

        @RenderBody()      

        <footer>
            @*<p>&copy; 2018 - EightQueenProblem</p>*@
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EightQueenProblem/Views/SolveProblem/Index.cshtml
@{
    ViewData["Title"] = "Solution8QueenProblem";
}

<style>
    h3 {
        text-align: center;
        color: grey;
        color: #447cff;
    }
</style>

<br />

@*<h3>Enter Chess Board Dimension</h3>
<br />
<div>
    <div class="form-group">
        <input class="form-control inputCustom" id="getSize" />
    </div>
    <button id="getResult" type="button" onclick="startChess()" class="btn btn-default btn-lg btn-block"> Get Result </button>
</div>
<br />*@

<!-- Modal START-->
<button type="button" class="btn btn-default btn-lg" id="myBtn">Solve n-Queens Problem</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h3>Enter Chess Board Dimension</h3>
                <br />
                <div>
                    <form id="myForm">
                        <input  id="getSize" type="number" min="4" max="10" class="form-control inputCustom" required/>
                    </form>
                    <br />
                    <button id="getResult"  onclick="startChess();" type="button" class="btn btn-primary btn-lg btn-block"> Get Result </button>
                </div>
                <br />
                <div id="textStatus">
                    <p id="textVal" style="text-align:center"></p>
                </div>             
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal END-->

<div id="detailsDiv">

</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#myBtn").click(function () {
                $("#myModal").modal();
            });
        });       
    </script>

    <script type="text/javascript">
        //VARIABLE DECLARATION
        
        var n = 0;
        var chessBoard = new Array();
        var chessBoardTemp = new Array();       
        
        function startChess() {
            
            console.log("start chess called");           
            n = $('#getSize').val();

            if (isNaN(n) || n <= 3 || n > 10) {
                textValidation = "Input number is not valid. Allowed number is between 4 and 10.";   
                clearInput();
            }
            else {
                textValidation = "Input number is OK.";
                console.log(n);
                createChess();
                find(0, 0);            
                clearInput();
            }
            document.getElementById("textVal").innerHTML = textValidation;
        }

        //CREATE CHESS FUNCTION
        function createChess()
        {
            console.log("create chess called");

            for (let i = 0; i < n; i++) {
                chessBoard[i] = new Array();
                for (let j = 0; j < n; j++) {
                    chessBoard[i][j] = 0;
                }
            }
        }

        //PRINT TEMP CHESSBOARD IN VIEW
        function writeChess(inValue) {
            for (let i = 0; i < n; i++) {
                for (let j = 0; j < n; j++) {
                    document.write("<a>   " + inValue[i][j] + "   <a>");
                }
                document.write("<br />")
            }
            document.write("<br>");
        }

        //COPY FUNCTION
        function copy(inValue) {
            for (let i = 0; i < inValue.length; i++) {
                chessBoardTemp[i] = inValue[i].slice();
            }
            return chessBoardTemp;
        }

        //CHECK FUNCTION FOR FREE POSITION
        function check(row, col) {
            // Checks the up direction
            for (var i = 0; i < row; i++) {
                if (chessBoard[i][col] === 1) {
                    return false;
                }
                //chessBoard[i][col] = 'X';
            }

            // Checks the left diagonal direction
            for (var i = row, j = col; i >= 0 && j >= 0; i-- , j--) {
                if (chessBoard[i][j] === 1) {
                    return false;
                }
            }

            // Checks the right diagonal direction
            for (var i = row, j = col; i >= 0 && j < n; i-- , j++) {
                if (chessBoard[i][j] === 1) {
                    return false;
                }
            }
            return true;
        }

        function getField(inValue)
        {
            var chessBoardFild = new Array();

            for (var i = 0; i < n; i++)
            {
                for (var j = 0; j < n; j++)
                {
                    if (inValue[i][j])
                    {
                        chessBoardFild.push({ row: i, col: j });
                    }
                }
            }
            return chessBoardFild;
        }

        function ViewAllSolution(inValue)
        {
            let combination;
            combination = {
                'Size': n,
                'QueenPositions': getField(inValue)
            }

            console.log(combination);

            $.ajax({
                    url: '@Url.Action("ViewAllSolution", "SolveProblem")',
                    type: "POST",
                    cache: false,
                    contentType: 'application/json',
                    //dataType: "json",
                    data: JSON.stringify(combination),                  

                    success: function (result) {
                        $('#detailsDiv').append(result);
                        console.log("GetChessGame success");
                        hidemodal();
                    },

                    error: function (response) {
                        $('#GetChessGame');
                        console.log("GetChessGame error", response);
                        hidemodal();
                    }
            });
        }

        //REC FILIP
        function find(row, col)
        {

            console.log(row, col, 'Started');

            if (row >= n) {
                var tempSolution = new Array();
                tempSolution = copy(chessBoard);
                //writeChess(tempSolution);
                //this.tempSolution.push(this.tempSolution.slice());
                ViewAllSolution(tempSolution);
                return;
            }

            if (col >= n) {
                return;
            }

            let isValid = check(row, col);

            if (isValid) {
                chessBoard[row][col] = 1;
                find(row + 1, 0);
                console.log(row, col, 'Has continued');
                chessBoard[row][col] = 0;
            }

            this.find(row, col + 1);

            console.log(row, col, 'Done');

        }

        function hidemodal() {
            console.log('Modal hide');
            $('#myModal').modal('hide');
        }

        function clearInput() {
            document.getElementById("myForm").reset();
        }

        function fade_out() {
            $("#textStatus").fadeOut().empty();
        }
    </script>
}

EightQueenProblem/Views/SolveProblem/_ViewAllSolution.cshtml
@model EightQueenProblem.Models.ChessModel.Chess

<style>
    .dot {
        height: 80%;
        width: 80%;
    }

    table, th, td {
        border: 1px solid #9f9f9f;
    }

    table, td {
        text-align: center;
    }

    #chessboard {
        padding: 0px;
        margin: 0 auto;
        border: 2px solid #7c7c7c;
    }

        #chessboard tr td {
            width: 60px;
            height: 60px;
        }

        #chessboard tr:nth-child(2n) td:nth-child(2n+1) {
            background: #9f9f9f;
        }

        #chessboard tr:nth-child(2n+1) td:nth-child(2n) {
            background: #9f9f9f;
        }
</style>

@*<div>
    TEST 1

    @for (int i = 0; i < @Model.Size; i++)
    {
        <div>TEST  2</div>
    }

</div>*@

<div>
    <table id="chessboard">
        @for (int i = 0; i < Model.Size; i++)
        {
            <tr>
                @for (int j = 0; j < Model.Size; j++)
                {
                    <td>
                        @if (Model.QueenPositions.Any(x => i == x.row && j == x.col))
                        {
                            <img class="dot" src="~/images/queen.png">
                        }
                    </td>
                }
            </tr>
        }
        <br />
    </table>
</div>

@section Scripts{

}